"""add language to posts

Revision ID: 29100b2beed8
Revises: b4dbd115b59c
Create Date: 2020-09-20 12:16:14.623912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29100b2beed8'
down_revision = 'b4dbd115b59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
